#ifndef LIBCALCULATOR_GLOBAL_H
#define LIBCALCULATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBCALCULATOR_LIBRARY)
#  define LIBCALCULATOR_EXPORT Q_DECL_EXPORT
#else
#  define LIBCALCULATOR_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBCALCULATOR_GLOBAL_H
